### ISSUE TITLE
using `main_groupclf.py` train adult, loss contain NaN.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [naver-ai/cgl_fairness#4]
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/b17ee548-ea3c-42b1-a844-0ad8102b2876)
The `nan` loss made the acc a rapid decrease.

And then I use command:
```
python main_groupclf.py --model mlp --method scratch \
    --dataset adult \
    --mode eval \
    --version groupclf_val \
    --sv 0.8
```
got this:
```
WARNING:root:Missing Data: 3620 rows removed from AdultDataset.
mode : test
# of 0 group data :  [10421  1330]
# of 1 group data :  [16763  7663]
preprocessing for ssl...
count the number of data newly!
mode : test
# of 0 group data :  [2084  265]
# of 1 group data :  [3352 1532]
WARNING:root:Missing Data: 3620 rows removed from AdultDataset.
mode : train
# of 0 group data :  [10421  1330]
# of 1 group data :  [16763  7663]
preprocessing for ssl...
count the number of data newly!
mode : train
# of 0 group data :  [6669  852]
# of 1 group data :  [10728  4904]
# of test data : 7233
# of train data : 23153
Dataset loaded.
# of classes, # of groups : 2, 2
Evaluation ----------------
WARNING:root:Missing Data: 3620 rows removed from AdultDataset.
mode : train
# of 0 group data :  [10421  1330]
# of 1 group data :  [16763  7663]
test acc : 0.32476150974699297
val acc : 0.3248143671213953
11751 24426
Traceback (most recent call last):
  File "/data1/cgl_fairness/main_groupclf.py", line 328, in <module>
    main()
  File "/data1/cgl_fairness/main_groupclf.py", line 306, in main
    opt_thres = predict_thres(results['probs'], results['true_idxs'], results['false_idxs'], val_idxs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/cgl_fairness/main_groupclf.py", line 98, in predict_thres
    r = measure_ood(val_true_maxprob.numpy(), val_false_maxprob.numpy())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/cgl_fairness/main_groupclf.py", line 71, in measure_ood
    fpr, tpr, thresholds = metrics.roc_curve(labels, preds, pos_label=1)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/metrics/_ranking.py", line 1095, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/metrics/_ranking.py", line 810, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/utils/validation.py", line 200, in assert_all_finite
    _assert_all_finite(
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/data1/micromamba/envs/fair/lib/python3.11/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
```

So the "nan" in the loss prevents us from proceeding to the next step.

**Comment by sangwon-jung94** [comment]
Thank you for the issue. 
We fixed bugs in our code. 
For Adult dataset, set the size of mini-batch `batch_size` as 1024.

**Comment by Ethan-Chen-plus** [comment]
Thank you @sangwon79 . But there's still `Nan` in the result. I use one way instead to solve this problem by adding two lines in `main_groupclf.py`:
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/1418b4e7-8aea-48c6-8f72-aecd75dc416e)


However I think the root cause is the version of `torch`, 'cudnn' or other things not direct related to the code, so the `requirement.txt` may be necessary.
